spring:
  application:
    name: ktool-workflow
  thymeleaf:
    cache: false
  
  datasource:
    url: jdbc:h2:file:./data/ktool-workflow-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    cl.kanopus.workflow: DEBUG
    org.springframework.security: INFO
